services:
  - name: CieluxApplication
    dockerfile: Dockerfile
    disk: 1
    env:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx400m"  # Limite la mémoire utilisée à 400 Mo

    ports:
      - 4005:4005
    routes:
      - path: /target
        command: java -jar target/demo.jar
    volumes:
      - name: data
        path: /data